/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface BLSGunInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MAX_LEAVES"
      | "TREE_DEPTH"
      | "filledSubtrees"
      | "getCommitmentCount"
      | "getMerkleRoot"
      | "isNullifierSpent"
      | "nextLeafIndex"
      | "nullifiers"
      | "privateTransfer"
      | "root"
      | "shield"
      | "unshield"
      | "verifier"
      | "zeroHashes"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "PrivateTransfer" | "Shield" | "Unshield"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "MAX_LEAVES",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TREE_DEPTH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "filledSubtrees",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCommitmentCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMerkleRoot",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isNullifierSpent",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "nextLeafIndex",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nullifiers",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "privateTransfer",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "root", values?: undefined): string;
  encodeFunctionData(functionFragment: "shield", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "unshield",
    values: [BytesLike, AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "verifier", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "zeroHashes",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "MAX_LEAVES", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "TREE_DEPTH", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "filledSubtrees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCommitmentCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMerkleRoot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isNullifierSpent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextLeafIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "nullifiers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "privateTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "root", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "shield", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "unshield", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "verifier", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "zeroHashes", data: BytesLike): Result;
}

export namespace PrivateTransferEvent {
  export type InputTuple = [nullifier: BytesLike, outputCommitment: BytesLike];
  export type OutputTuple = [nullifier: string, outputCommitment: string];
  export interface OutputObject {
    nullifier: string;
    outputCommitment: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ShieldEvent {
  export type InputTuple = [
    sender: AddressLike,
    commitment: BytesLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    sender: string,
    commitment: string,
    amount: bigint
  ];
  export interface OutputObject {
    sender: string;
    commitment: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnshieldEvent {
  export type InputTuple = [
    nullifier: BytesLike,
    recipient: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    nullifier: string,
    recipient: string,
    amount: bigint
  ];
  export interface OutputObject {
    nullifier: string;
    recipient: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BLSGun extends BaseContract {
  connect(runner?: ContractRunner | null): BLSGun;
  waitForDeployment(): Promise<this>;

  interface: BLSGunInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MAX_LEAVES: TypedContractMethod<[], [bigint], "view">;

  TREE_DEPTH: TypedContractMethod<[], [bigint], "view">;

  filledSubtrees: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  getCommitmentCount: TypedContractMethod<[], [bigint], "view">;

  getMerkleRoot: TypedContractMethod<[], [string], "view">;

  isNullifierSpent: TypedContractMethod<
    [nullifier: BytesLike],
    [boolean],
    "view"
  >;

  nextLeafIndex: TypedContractMethod<[], [bigint], "view">;

  nullifiers: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  privateTransfer: TypedContractMethod<
    [nullifier: BytesLike, outputCommitment: BytesLike, proof: BytesLike],
    [void],
    "nonpayable"
  >;

  root: TypedContractMethod<[], [string], "view">;

  shield: TypedContractMethod<[commitment: BytesLike], [void], "payable">;

  unshield: TypedContractMethod<
    [
      nullifier: BytesLike,
      recipient: AddressLike,
      amount: BigNumberish,
      proof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  verifier: TypedContractMethod<[], [string], "view">;

  zeroHashes: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MAX_LEAVES"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TREE_DEPTH"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "filledSubtrees"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getCommitmentCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getMerkleRoot"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "isNullifierSpent"
  ): TypedContractMethod<[nullifier: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "nextLeafIndex"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "nullifiers"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "privateTransfer"
  ): TypedContractMethod<
    [nullifier: BytesLike, outputCommitment: BytesLike, proof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "root"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "shield"
  ): TypedContractMethod<[commitment: BytesLike], [void], "payable">;
  getFunction(
    nameOrSignature: "unshield"
  ): TypedContractMethod<
    [
      nullifier: BytesLike,
      recipient: AddressLike,
      amount: BigNumberish,
      proof: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifier"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "zeroHashes"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  getEvent(
    key: "PrivateTransfer"
  ): TypedContractEvent<
    PrivateTransferEvent.InputTuple,
    PrivateTransferEvent.OutputTuple,
    PrivateTransferEvent.OutputObject
  >;
  getEvent(
    key: "Shield"
  ): TypedContractEvent<
    ShieldEvent.InputTuple,
    ShieldEvent.OutputTuple,
    ShieldEvent.OutputObject
  >;
  getEvent(
    key: "Unshield"
  ): TypedContractEvent<
    UnshieldEvent.InputTuple,
    UnshieldEvent.OutputTuple,
    UnshieldEvent.OutputObject
  >;

  filters: {
    "PrivateTransfer(bytes32,bytes32)": TypedContractEvent<
      PrivateTransferEvent.InputTuple,
      PrivateTransferEvent.OutputTuple,
      PrivateTransferEvent.OutputObject
    >;
    PrivateTransfer: TypedContractEvent<
      PrivateTransferEvent.InputTuple,
      PrivateTransferEvent.OutputTuple,
      PrivateTransferEvent.OutputObject
    >;

    "Shield(address,bytes32,uint256)": TypedContractEvent<
      ShieldEvent.InputTuple,
      ShieldEvent.OutputTuple,
      ShieldEvent.OutputObject
    >;
    Shield: TypedContractEvent<
      ShieldEvent.InputTuple,
      ShieldEvent.OutputTuple,
      ShieldEvent.OutputObject
    >;

    "Unshield(bytes32,address,uint256)": TypedContractEvent<
      UnshieldEvent.InputTuple,
      UnshieldEvent.OutputTuple,
      UnshieldEvent.OutputObject
    >;
    Unshield: TypedContractEvent<
      UnshieldEvent.InputTuple,
      UnshieldEvent.OutputTuple,
      UnshieldEvent.OutputObject
    >;
  };
}
