/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../common";
import type { MerkleTree, MerkleTreeInterface } from "../MerkleTree";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "MAX_LEAVES",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "TREE_DEPTH",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "filledSubtrees",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "nextLeafIndex",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "root",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "zeroHashes",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561000f575f5ffd5b505f805560015b60148111610088576100625f61002d600184610131565b6015811061003d5761003d610109565b01545f61004b600185610131565b6015811061005b5761005b610109565b01546100da565b5f826015811061007457610074610109565b01558061008081610144565b915050610016565b505f5b601481116100ce575f81601581106100a5576100a5610109565b0154601582601581106100ba576100ba610109565b0155806100c681610144565b91505061008b565b50601454602b5561015c565b604080516020808201859052818301849052825180830384018152606090920190925280519101205b92915050565b634e487b7160e01b5f52603260045260245ffd5b634e487b7160e01b5f52601160045260245ffd5b818103818111156101035761010361011d565b5f600182016101555761015561011d565b5060010190565b610249806101695f395ff3fe608060405234801561000f575f5ffd5b5060043610610060575f3560e01c8063082febf0146100645780630be4f4221461007e5780637ac5476714610087578063ebf0c7171461009a578063f1650536146100a3578063f178e47c146100ab575b5f5ffd5b61006c6100be565b60405190815260200160405180910390f35b61006c602a5481565b61006c6100953660046100f1565b6100cd565b61006c602b5481565b61006c601481565b61006c6100b93660046100f1565b6100e2565b6100ca60146002610201565b81565b5f81601581106100db575f80fd5b0154905081565b601581601581106100db575f80fd5b5f60208284031215610101575f5ffd5b5035919050565b634e487b7160e01b5f52601160045260245ffd5b6001815b60018411156101575780850481111561013b5761013b610108565b600184161561014957908102905b60019390931c928002610120565b935093915050565b5f8261016d575060016101fb565b8161017957505f6101fb565b816001811461018f5760028114610199576101b5565b60019150506101fb565b60ff8411156101aa576101aa610108565b50506001821b6101fb565b5060208310610133831016604e8410600b84101617156101d8575081810a6101fb565b6101e45f19848461011c565b805f19048211156101f7576101f7610108565b0290505b92915050565b5f61020c838361015f565b939250505056fea26469706673582212204907c713cc7e9c67da1d643e9580833c097a26f2d5afb0e0f7b170ce0ace86a764736f6c634300081b0033";

type MerkleTreeConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MerkleTreeConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MerkleTree__factory extends ContractFactory {
  constructor(...args: MerkleTreeConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      MerkleTree & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): MerkleTree__factory {
    return super.connect(runner) as MerkleTree__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MerkleTreeInterface {
    return new Interface(_abi) as MerkleTreeInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): MerkleTree {
    return new Contract(address, _abi, runner) as unknown as MerkleTree;
  }
}
