export const blsGunAbi = [
  {
    type: "event",
    name: "Shield",
    inputs: [
      { name: "sender", type: "address", indexed: true },
      { name: "commitment", type: "bytes32", indexed: true },
      { name: "ephPubKeyX", type: "bytes32", indexed: false },
      { name: "ephPubKeyY", type: "bytes32", indexed: false },
      { name: "viewTag", type: "uint8", indexed: false },
      { name: "encryptedAmount", type: "uint128", indexed: false },
    ],
  },
  {
    type: "event",
    name: "PrivateTransfer",
    inputs: [
      { name: "nullifier", type: "bytes32", indexed: true },
      { name: "outputCommitment", type: "bytes32", indexed: true },
      { name: "ephPubKeyX", type: "bytes32", indexed: false },
      { name: "ephPubKeyY", type: "bytes32", indexed: false },
      { name: "viewTag", type: "uint8", indexed: false },
      { name: "encryptedAmount", type: "uint128", indexed: false },
    ],
  },
  {
    type: "event",
    name: "Unshield",
    inputs: [
      { name: "nullifier", type: "bytes32", indexed: true },
      { name: "recipient", type: "address", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
    ],
  },
  {
    type: "function",
    name: "shield",
    stateMutability: "payable",
    inputs: [
      { name: "commitment", type: "bytes32" },
      { name: "ephPubKeyX", type: "bytes32" },
      { name: "ephPubKeyY", type: "bytes32" },
      { name: "viewTag", type: "uint8" },
      { name: "encryptedAmount", type: "uint128" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "privateTransfer",
    stateMutability: "nonpayable",
    inputs: [
      { name: "nullifier", type: "bytes32" },
      { name: "inputCommitment", type: "bytes32" },
      { name: "outputCommitment", type: "bytes32" },
      { name: "proof", type: "bytes" },
      { name: "ephPubKeyX", type: "bytes32" },
      { name: "ephPubKeyY", type: "bytes32" },
      { name: "viewTag", type: "uint8" },
      { name: "encryptedAmount", type: "uint128" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "unshield",
    stateMutability: "nonpayable",
    inputs: [
      { name: "nullifier", type: "bytes32" },
      { name: "inputCommitment", type: "bytes32" },
      { name: "recipient", type: "address" },
      { name: "amount", type: "uint256" },
      { name: "proof", type: "bytes" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "isNullifierSpent",
    stateMutability: "view",
    inputs: [{ name: "nullifier", type: "bytes32" }],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    type: "function",
    name: "getMerkleRoot",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "bytes32" }],
  },
  {
    type: "function",
    name: "getCommitmentCount",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
] as const;
